### ISSUE TITLE
invalid literal for int() with base 10: 'HLT'

### ISSUE THREAD

**Issue by fayazhussainalibaig** [Esri/Utility-Data-Management-Support-Tools#32]
Error running Summarise Errors.

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "XXXXXX\Tools\Utility-Data-Management-Support-Tools\UtilityDataManagementSupport.atbx\udms\esri.py", line 135, in wrapper
  File "XXXXXX\Tools\Utility-Data-Management-Support-Tools\UtilityDataManagementSupport.atbx\udms\logic\__init__.py", line 435, in summarize_errors
  File "XXXXXX\Tools\Utility-Data-Management-Support-Tools\UtilityDataManagementSupport.atbx\udms\logic\errors.py", line 507, in main
  File "XXXXXX\Tools\Utility-Data-Management-Support-Tools\UtilityDataManagementSupport.atbx\udms\logic\errors.py", line 473, in gather_errors
  File "C:\Users\baigf\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\pandas\core\frame.py", line 563, in __init__
    data = list(data)
  File "XXXXXX\Tools\Utility-Data-Management-Support-Tools\UtilityDataManagementSupport.atbx\udms\logic\errors.py", line 261, in read_errors
  File "XXXXXX\Tools\Utility-Data-Management-Support-Tools\UtilityDataManagementSupport.atbx\udms\logic\errors.py", line 214, in extract_error_message
ValueError: invalid literal for int() with base 10: 'HLT'

**Comment by pLeBlanc93** [comment]
Hi, what version of Pro are you using?

**Comment by fayazhussainalibaig** [comment]
Thanks for reaching out Paul.

We have used  both 2.9.1 and 2.9.5 versions of ArcGIS Pro .

Thanks,
Fayaz

**Comment by MikeMillerGIS** [comment]
I pushed a new version to https://github.com/Esri/Utility-Data-Management-Support-Tools/blob/2.9/UtilityDataManagementSupport.atbx.  Can you give that a try?

**Comment by fayazhussainalibaig** [comment]
Thank You Michael.

This version of tool ran successfully .

**Comment by MikeMillerGIS** [comment]
this is now in the 2.9 and 3.1 version posted
