### ISSUE TITLE
Export UN matrix error

### ISSUE THREAD

**Issue by gprocino** [Esri/Utility-Data-Management-Support-Tools#34]
**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
- Pro 2.9.5

Export Matrix
=====================
Parameters

Input Network     C:\ArcGIS\XXX\XXX.gdb\XXX\xXXXXX
Matrix Workbook     C:\ArcGIS\unmatrix.xlsx
Matrix Options     ASSOCIATION_ROLES;CATEGORIES;TERMINALS;RULES
=====================
Messages

Start Time: giovedì 16 marzo 2023 16:27:12
udms 2.9.2
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms\esri.py", line 274, in wrapper
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms_pt\common\wrappers.py", line 459, in wrapper
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms\logic\__init__.py", line 409, in export_matrix
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms\logic\matrix\save.py", line 650, in main
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms\logic\matrix\save.py", line 392, in add_rule_sheets
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms\logic\matrix\save.py", line 299, in create_empty_matrix
  File "C:\Users\PRCGPP78R\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\pandas\core\generic.py", line 5478, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\xx\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\xx\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\pandas\core\internals\managers.py", line 221, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 70 elements, new values have 69 elements

Failed script (null)...
Failed to execute (ExportUtilityNetworkMatrix).
Failed at giovedì 16 marzo 2023 16:27:20 (Elapsed Time: 7,88 seconds)
---------------------------
udms 2.9.2
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms\esri.py", line 274, in wrapper
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms_pt\common\wrappers.py", line 459, in wrapper
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms\logic\__init__.py", line 409, in export_matrix
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms\logic\matrix\save.py", line 650, in main
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms\logic\matrix\save.py", line 392, in add_rule_sheets
  File "C:\ArcGIS_resource\Utility-Data-Management-Support-Tools-2.9\Utility-Data-Management-Support-Tools-2.9\UtilityDataManagementSupport.atbx\udms\logic\matrix\save.py", line 299, in create_empty_matrix
  File "C:\Users\xx\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\pandas\core\generic.py", line 5478, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\xx\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\xx\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\pandas\core\internals\managers.py", line 221, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 70 elements, new values have 69 elements
Failed script (null)...
Failed to execute (ExportUtilityNetworkMatrix).

**Comment by MikeMillerGIS** [comment]
Can you right click your Feature Dataset and select Export XML.  Select Schema only and send that to us?

**Comment by MikeMillerGIS** [comment]
Thank you for the xml file.  I found the issue.  We never accounted for rules that are present, but do not have a matching AssetGroup/AssetType.  Here is a version of the 2.9.2 toolset that handles that issue.
[UtilityDataManagementSupport.zip](https://github.com/Esri/Utility-Data-Management-Support-Tools/files/11000680/UtilityDataManagementSupport.zip)
