### ISSUE TITLE
import matrix error

### ISSUE THREAD

**Issue by gprocino** [Esri/Utility-Data-Management-Support-Tools#39]
hi,
I tried to export/import matrix changing just one parameter in categories sheet but the following error appear:
Traceback (most recent call last):
  File "C:\ArcGIS\WaterF_v13\Toolboxes\UtilityDataManagementSupport_31.atbx#ImportUtilityNetworkMatrix_udms.py", line 12, in <module>
  File "C:\ArcGIS\WaterF_v13\Toolboxes\UtilityDataManagementSupport_31.atbx\udms\esri.py", line 277, in wrapper
  File "C:\ArcGIS\WaterF_v13\Toolboxes\UtilityDataManagementSupport_31.atbx\udms_pt\common\wrappers.py", line 462, in wrapper
  File "C:\ArcGIS\WaterF_v13\Toolboxes\UtilityDataManagementSupport_31.atbx\udms\logic\__init__.py", line 440, in import_matrix
  File "C:\ArcGIS\WaterF_v13\Toolboxes\UtilityDataManagementSupport_31.atbx\udms\logic\matrix\load.py", line 316, in main
  File "C:\ArcGIS\WaterF_v13\Toolboxes\UtilityDataManagementSupport_31.atbx\udms\logic\matrix\load.py", line 331, in _utility_network
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by MikeMillerGIS** [comment]
I am pretty sure we solved that error, can you try the version in this branch?
https://github.com/Esri/Utility-Data-Management-Support-Tools/tree/3.1.1.1

https://github.com/Esri/Utility-Data-Management-Support-Tools/blob/3.1.1.1/UtilityDataManagementSupport.atbx

**Comment by gprocino** [comment]
It's correct. thank you
