### ISSUE TITLE
export matrix error

### ISSUE THREAD

**Issue by gprocino** [Esri/Utility-Data-Management-Support-Tools#41]
Hi,
after step [4] of Configuring Utility Network (https://pro.arcgis.com/en/pro-app/latest/help/data/utility-network/configure-a-utility-network.htm) if I try to export matrix - with v.3.1.1.2  - with Rules option the following  error appear:
Traceback (most recent call last):
  File "C:\ArcGIS\17_xx\UtilityDataManagementSupport_3111.atbx#ExportUtilityNetworkMatrix_udms.py", line 12, in <module>
  File "C:\ArcGIS\17_xx\UtilityDataManagementSupport_31.atbx\udms\esri.py", line 277, in wrapper
  File "C:\ArcGIS\17_xx\UtilityDataManagementSupport_31.atbx\udms_pt\common\wrappers.py", line 462, in wrapper
  File "C:\ArcGIS\17_xx\UtilityDataManagementSupport_31.atbx\udms\logic\__init__.py", line 404, in export_matrix
  File "C:\ArcGIS\17_xx\UtilityDataManagementSupport_31.atbx\udms\logic\matrix\save.py", line 651, in main
  File "C:\ArcGIS\17_xx\UtilityDataManagementSupport_31.atbx\udms\logic\matrix\save.py", line 353, in add_rule_sheets
  File "C:\ArcGIS\17_xx\UtilityDataManagementSupport_31.atbx\udms\logic\matrix\save.py", line 98, in _get_rules
ValueError: not enough values to unpack (expected 2, got 0)

The error occurs if I haven't rules but if I try to add just  a single rule (such as a junction-edge rule) the matrix is exported partiality (there aren't Containment and Structural Attachment sheets)

**Comment by MikeMillerGIS** [comment]
looks like it is loading the old code, see how it references C:\ArcGIS\17_xx\UtilityDataManagementSupport_3111.atbx and then C:\ArcGIS\17_xx\UtilityDataManagementSupport_31.atbx?  Can you delete C:\ArcGIS\17_xx\UtilityDataManagementSupport_31.atbx and try again?

**Comment by MikeMillerGIS** [comment]
I cannot repo on a UN with no rules, so I hope it is just the atbx loading the old code

**Comment by gprocino** [comment]
Hi Mike, using UtilityDataManagementSupport_3112.atbx on a UN without rules and association (with all matrix option) the matrix is exported partiality becouse there aren't Containment and Structural Attachment sheets.

**Comment by MikeMillerGIS** [comment]
Those sheets are not added as there are no AG/ATs with a structure or containment association role.  Closing as As-Designed
