### ISSUE TITLE
Change GDB Spatial reference failed - with error 99999

### ISSUE THREAD

**Issue by holubvl3** [Esri/Utility-Data-Management-Support-Tools#46]
**Describe the bug**
Hello,

I am using the latest UN Water network solution data model (build for 3.1). When I want to convert it from default coordinate system to Czech native coordinate system S-JTSK EN, EPSG:5514 (but the same is for input of Web Mercator with EPSG: 3857), during the process when copying some attachments - see the images below. Beyond that step I wasn´t able to get.

The error in the Message log states this: "PermissionError: [WinError 32] The process cannot access the file because it is currently in use by another process: 'C:\\Users\\vholubec\\AppData\\Local\\Temp\\ArcGISProTemp37960\\tmp_fd77efh\\XML.gdb\\ _gdb.NBVHOLUBEC.21864.37960.sr.lock'"

Which is weird, since the Temp folder has created this Pro instance (no other instances are running there, I also tried to clean up the Temp and repeat, but it hasn't helped)

The full log is: 

EXCEPTION
Traceback (most recent call last):
  File "D:\Projekty\UN\Water_Distribution_Utility_Network_FoundationV1_3\Toolboxes\UtilityDataManagementSupport_31.atbx\udms_pt\utility_network\ap.py", line 779, in create_new_gdb
    arcpy.ImportXMLWorkspaceDocument_management(
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 24225, in ImportXMLWorkspaceDocument
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 24222, in ImportXMLWorkspaceDocument
    retval = convertArcObjectToPythonObject(gp.ImportXMLWorkspaceDocument_management(*gp_fixargs((target_geodatabase, in_file, import_type, config_keyword), True)))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: [ERROR 999999:](javascript:void(0);) Something unexpected caused the tool to fail. Contact Esri Technical Support (http://esriurl.com/support) to Report a Bug, and refer to the error help for potential solutions or workarounds.
The domain was not found. [Yes_No_Not_Applicable]
The domain was not found. [Yes_No]
The domain was not found. [Water_Well_Diameter]
The domain was not found. [Water_Valve_Type]
The domain was not found. [Water_Valve_Surface_Type]
The domain was not found. [Water_Type]
The domain was not found. [Water_Service_Material]
The domain was not found. [Water_Service_Diameter]
The domain was not found. [Water_Pump_Type]
The domain was not found. [Water_Pump_Diameter]
The domain was not found. [Water_Meter_Diameter]
The domain was not found. [Water_Main_Material]
The domain was not found. [Water_Main_Diameter]
The domain was not found. [Water_Hydrant_Service_Diameter]
The domain was not found. [Water_Hydrant_Nozzle_Diameter]
The domain was not found. [Water_Fitting_Diameter]
The domain was not found. [Water_Fire_Hydrant_Manufacturer]
The domain was not found. [Water_Diameter]
The domain was not found. [Symbol_Rotation]
The domain was not found. [Spatial_Source]
The domain was not found. [Spatial_Confidence]
The domain was not found. [Pipe_Access_Point_Size]
The domain was not found. [Pipe_Access_Point_Depth]
The domain was not found. [Pipeline_Valve_Status]
The domain was not found. [Pipeline_Valve_Close_Direction]
The domain was not found. [Pipeline_Casing_Fill_Type]
The domain was not found. [Pipeline_Casing_Diameter]
The domain was not found. [Network_5_UnknownAssetType]
The domain was not found. [Network_5_TierTopologyType]
The domain was not found. [Network_5_TierName]
The domain was not found. [Network_5_TerminalNames]
The domain was not found. [Network_5_IsSubnetworkController]
The domain was not found. [Network_5_IsDirty]
The domain was not found. [Network_5_IsDeleted]
The domain was not found. [Network_5_IsContentVisible]
The domain was not found. [Network_5_IsConnected]
The domain was not found. [Network_5_FeatureSourceID]
The domain was not found. [Network_5_AssociationStatus]
The domain was not found. [Lifecycle_Status]
The domain was not found. [Lifecycle_Combined]
The domain was not found. [Groundbed_Depth]
The domain was not found. [CP_Wire_Gauge]
The domain was not found. [CP_Traceability]
The domain was not found. [CP_Test_Point_Wire_Count]
The domain was not found. [CP_Rectifier_Manufacturer_int]
The domain was not found. [CP_Rectifier_Cooling_Method]
The domain was not found. [CP_Anode_Weight]
The domain was not found. [CP_Anode_Material_short]
The domain was not found. [Boolean]
The domain was not found. [Bonded_Insulated]
The domain was not found. [Asset_Type_Water_Line_Water_Main]
The domain was not found. [Asset_Type_Water_Line_Test_Lead_Wire]
The domain was not found. [Asset_Type_Water_Line_Service]
The domain was not found. [Asset_Type_Water_Line_Rectifier_Cable]
The domain was not found. [Asset_Type_Water_Line_Bonding_Line]
The domain was not found. [Asset_Type_Water_Junction_Wire_Junction]
The domain was not found. [Asset_Type_Water_Junction_Insulation_Junction]
The domain was not found. [Asset_Type_Water_Junction_Fitting]
The domain was not found. [Asset_Type_Water_Device_Test_Point]
The domain was not found. [Asset_Type_Water_Device_System_Valve]
The domain was not found. [Asset_Type_Water_Device_System_Meter]
The domain was not found. [Asset_Type_Water_Device_Supply]
The domain was not found. [Asset_Type_Water_Device_Storage]
The domain was not found. [Asset_Type_Water_Device_Station]
The domain was not found. [Asset_Type_Water_Device_Service_Valve]
The domain was not found. [Asset_Type_Water_Device_Service_Meter]
The domain was not found. [Asset_Type_Water_Device_Service_Connection]
The domain was not found. [Asset_Type_Water_Device_Rectifier]
The domain was not found. [Asset_Type_Water_Device_Pump]
The domain was not found. [Asset_Type_Water_Device_Pressure_Valve]
The domain was not found. [Asset_Type_Water_Device_Outlet]
The domain was not found. [Asset_Type_Water_Device_Monitoring]
The domain was not found. [Asset_Type_Water_Device_Injection_Facility]
The domain was not found. [Asset_Type_Water_Device_Groundbed]
The domain was not found. [Asset_Type_Water_Device_Flushing_and_Blow_Off]
The domain was not found. [Asset_Type_Water_Device_Flow_Valve]
The domain was not found. [Asset_Type_Water_Device_Fire_Hydrant]
The domain was not found. [Asset_Type_Water_Device_Filter]
The domain was not found. [Asset_Type_Water_Device_Controller]
The domain was not found. [Asset_Type_Water_Device_Anode]
The domain was not found. [Asset_Type_Water_Assembly_Pressure_Reducing_Station]
The domain was not found. [Asset_Type_Water_Assembly_Meter_Station]
The domain was not found. [Asset_Type_Water_Assembly_Hydrant]
The domain was not found. [Asset_Type_Water_Assembly_Horizontal_Valve]
The domain was not found. [Asset_Type_Water_Assembly_Blow_Off]
The domain was not found. [Asset_Type_Water_Assembly_Backflow]
The domain was not found. [Asset_Type_Water_Assembly_Air_Vacuum_and_Air_Release]
The domain was not found. [Asset_Type_Structure_Line_Pipeline_Casing]
The domain was not found. [Asset_Type_Structure_Junction_Pipe_Access_Point]
The domain was not found. [Asset_Type_Structure_Junction_Pipeline_Vault]
The domain was not found. [Asset_Type_Structure_Junction_Pipeline_Valve_Box]
The domain was not found. [Asset_Type_Structure_Junction_Pipeline_Pipe_Support]
The domain was not found. [Asset_Type_Structure_Junction_Pipeline_Pipe_Hanger]
The domain was not found. [Asset_Type_Structure_Junction_Pipeline_Anchor]
The domain was not found. [Asset_Type_Structure_Boundary_Water_Supply_Boundary]
The domain was not found. [Asset_Type_Structure_Boundary_Water_Storage_Boundary]
The domain was not found. [Asset_Type_Structure_Boundary_Water_Pump_Station_Boundary]
The domain was not found. [Asset_Type_Structure_Boundary_Pipeline_Pipe_Vault]
The domain was not found. [Asset_Owner]
The domain was not found. [Asset_Manager]
The domain was not found. [AP_Traversability_Scope]
The domain was not found. [AP_Trace_Types]
The domain was not found. [AP_Topology_Types]
The domain was not found. [AP_Tier_Types]
The domain was not found. [AP_Terminal_Traversability]
The domain was not found. [AP_Terminals_Classes]
The domain was not found. [AP_Subnetwork_Types]
The domain was not found. [AP_Subnetwork_Propagation]
The domain was not found. [AP_Subnetwork_Operators]
The domain was not found. [AP_Subnetwork_Functions]
The domain was not found. [AP_Subnetwork_Filters]
The domain was not found. [AP_Subnetwork_EditModes]
The domain was not found. [AP_Subnetwork_Combinations]
The domain was not found. [AP_Rule_Types]
The domain was not found. [AP_Linear_Classes]
The domain was not found. [AP_Edge_Policy]
The domain was not found. [AP_Domain_Networks]
The domain was not found. [AP_Boolean]
The domain was not found. [AP_Attribute_Types]
The domain was not found. [AP_AttributeRule_Types]
The domain was not found. [AP_Association_Types]
The domain was not found. [AP_Association_Semantics]
The domain was not found. [AP_Association_Roles]
The domain was not found. [AP_Association_Classes]
The domain was not found. [AP_All_Classes]
Failed to execute (ImportXMLWorkspaceDocument).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\shutil.py", line 632, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] Proces nemá přístup k souboru, neboť jej právě využívá jiný proces: 'C:\\Users\\vholubec\\AppData\\Local\\Temp\\ArcGISProTemp37960\\tmp_fd77efh\\XML.gdb\\_gdb.NBVHOLUBEC.21864.37960.sr.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projekty\UN\Water_Distribution_Utility_Network_FoundationV1_3\Toolboxes\UtilityDataManagementSupport_31.atbx\udms_pt\common\wrappers.py", line 159, in wrapper
    f = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projekty\UN\Water_Distribution_Utility_Network_FoundationV1_3\Toolboxes\UtilityDataManagementSupport_31.atbx\udms_pt\gptools\tools.py", line 129, in run
    out_gdb = change_spat.main(include_tables=include)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projekty\UN\Water_Distribution_Utility_Network_FoundationV1_3\Toolboxes\UtilityDataManagementSupport_31.atbx\udms_pt\utility_network\ap.py", line 845, in main
    gdb = self.create_new_gdb()
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projekty\UN\Water_Distribution_Utility_Network_FoundationV1_3\Toolboxes\UtilityDataManagementSupport_31.atbx\udms_pt\utility_network\ap.py", line 752, in create_new_gdb
    with tempfile.TemporaryDirectory() as temp_dir:
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\tempfile.py", line 943, in __exit__
    self.cleanup()
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\tempfile.py", line 947, in cleanup
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\tempfile.py", line 929, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\shutil.py", line 787, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\shutil.py", line 629, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\shutil.py", line 634, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\tempfile.py", line 893, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] Proces nemá přístup k souboru, neboť jej právě využívá jiný proces: 'C:\\Users\\vholubec\\AppData\\Local\\Temp\\ArcGISProTemp37960\\tmp_fd77efh\\XML.gdb\\_gdb.NBVHOLUBEC.21864.37960.sr.lock'
Failed script Change GDB Spatial Reference...
Failed to execute (ChangeGDBSpatialReference).

**To Reproduce**
1. Open the Solution
2. Download the toolbox from GitHUB - and one the too Change GDB Spatial Reference
3. Set the input - as in the screenshot below
4. Run the tool and wait.
5. See error

**Expected behavior**
It should convert the default asset package without error.

**Screenshots**

Settings of the tool: 
![image](https://github.com/Esri/Utility-Data-Management-Support-Tools/assets/47881982/d9cd3f38-dc93-4e0d-93de-c4c1d1e50618)

Last second before the fail
![image](https://github.com/Esri/Utility-Data-Management-Support-Tools/assets/47881982/2888dd1a-0b0b-4823-bb5d-29620a4c76be)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2, Czech
 - ArcGIS Pro 3.3.51532, Beta 2
 

**Additional context**

**Comment by MikeMillerGIS** [comment]
If you downloaded the tool from github, you need to remove all the old toolboxes from your machine and restart pro.  I think you have a mixed version of the tool and how it loads the python gets messed up.

**Comment by holubvl3** [comment]
Thank you @MikeMillerGIS  for flash answer. This hasn´t helped - I deleted the default tools toolboxes from the folder and from the project (kept just the one toolbox for Water tracing), clean up the temp folder and run again, but same error appeared.

**Comment by MikeMillerGIS** [comment]
can you post an updated error log?  I want to see if anything changed.  Make sure to restart pro.  The current error log shows the 3_1 toolbox, that is very suspicious.

**Comment by holubvl3** [comment]
Just one more addition @MikeMillerGIS.

1) I´ve opened new project and attached the folder with the UN data and toolbox.
2) Run the tool with almost default settings:

![image](https://github.com/Esri/Utility-Data-Management-Support-Tools/assets/47881982/0d2af79c-d709-4824-83b8-1db904443b33)

3) And it worked - great.
4) So, for test, in the output folder I renamed the FGDB and run again
5) I got a same error 99999

So, it looks like the Pro (maybe Python/maybe a geodatabase part) is unable to clean up/handle the lock during the process. And so it´s not about the input, about the project. 

Haven´t you seen the similar behavior before? Or is this issue rather for GP/Geodatabase/Python team? 

Also, I checked my old notes - and I´ve reported this for Pro 3.3 Alpha already on EAC (with no response). On the Alpha I´ve used the default toolbox form the solution available (I am sorry I forgot on it).



EXCEPTION
Traceback (most recent call last):
  File "D:\Projekty\UN\Water_Distribution_Utility_Network_FoundationV1_3\Esri_tools\UtilityDataManagementSupport.atbx\udms_pt\utility_network\ap.py", line 788, in create_new_gdb
    arcpy.ImportXMLWorkspaceDocument_management(
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 24225, in ImportXMLWorkspaceDocument
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 24222, in ImportXMLWorkspaceDocument
    retval = convertArcObjectToPythonObject(gp.ImportXMLWorkspaceDocument_management(*gp_fixargs((target_geodatabase, in_file, import_type, config_keyword), True)))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: [ERROR 999999:](javascript:void(0);) Something unexpected caused the tool to fail. Contact Esri Technical Support (http://esriurl.com/support) to Report a Bug, and refer to the error help for potential solutions or workarounds.
The domain was not found. [Yes_No_Not_Applicable]
The domain was not found. [Yes_No]
The domain was not found. [Water_Well_Diameter]
The domain was not found. [Water_Valve_Type]
The domain was not found. [Water_Valve_Surface_Type]
The domain was not found. [Water_Type]
The domain was not found. [Water_Service_Material]
The domain was not found. [Water_Service_Diameter]
The domain was not found. [Water_Pump_Type]
The domain was not found. [Water_Pump_Diameter]
The domain was not found. [Water_Meter_Diameter]
The domain was not found. [Water_Main_Material]
The domain was not found. [Water_Main_Diameter]
The domain was not found. [Water_Hydrant_Service_Diameter]
The domain was not found. [Water_Hydrant_Nozzle_Diameter]
The domain was not found. [Water_Fitting_Diameter]
The domain was not found. [Water_Fire_Hydrant_Manufacturer]
The domain was not found. [Water_Diameter]
The domain was not found. [Symbol_Rotation]
The domain was not found. [Spatial_Source]
The domain was not found. [Spatial_Confidence]
The domain was not found. [Pipe_Access_Point_Size]
The domain was not found. [Pipe_Access_Point_Depth]
The domain was not found. [Pipeline_Valve_Status]
The domain was not found. [Pipeline_Valve_Close_Direction]
The domain was not found. [Pipeline_Casing_Fill_Type]
The domain was not found. [Pipeline_Casing_Diameter]
The domain was not found. [Network_5_UnknownAssetType]
The domain was not found. [Network_5_TierTopologyType]
The domain was not found. [Network_5_TierName]
The domain was not found. [Network_5_TerminalNames]
The domain was not found. [Network_5_IsSubnetworkController]
The domain was not found. [Network_5_IsDirty]
The domain was not found. [Network_5_IsDeleted]
The domain was not found. [Network_5_IsContentVisible]
The domain was not found. [Network_5_IsConnected]
The domain was not found. [Network_5_FeatureSourceID]
The domain was not found. [Network_5_AssociationStatus]
The domain was not found. [Lifecycle_Status]
The domain was not found. [Lifecycle_Combined]
The domain was not found. [Groundbed_Depth]
The domain was not found. [CP_Wire_Gauge]
The domain was not found. [CP_Traceability]
The domain was not found. [CP_Test_Point_Wire_Count]
The domain was not found. [CP_Rectifier_Manufacturer_int]
The domain was not found. [CP_Rectifier_Cooling_Method]
The domain was not found. [CP_Anode_Weight]
The domain was not found. [CP_Anode_Material_short]
The domain was not found. [Boolean]
The domain was not found. [Bonded_Insulated]
The domain was not found. [Asset_Type_Water_Line_Water_Main]
The domain was not found. [Asset_Type_Water_Line_Test_Lead_Wire]
The domain was not found. [Asset_Type_Water_Line_Service]
The domain was not found. [Asset_Type_Water_Line_Rectifier_Cable]
The domain was not found. [Asset_Type_Water_Line_Bonding_Line]
The domain was not found. [Asset_Type_Water_Junction_Wire_Junction]
The domain was not found. [Asset_Type_Water_Junction_Insulation_Junction]
The domain was not found. [Asset_Type_Water_Junction_Fitting]
The domain was not found. [Asset_Type_Water_Device_Test_Point]
The domain was not found. [Asset_Type_Water_Device_System_Valve]
The domain was not found. [Asset_Type_Water_Device_System_Meter]
The domain was not found. [Asset_Type_Water_Device_Supply]
The domain was not found. [Asset_Type_Water_Device_Storage]
The domain was not found. [Asset_Type_Water_Device_Station]
The domain was not found. [Asset_Type_Water_Device_Service_Valve]
The domain was not found. [Asset_Type_Water_Device_Service_Meter]
The domain was not found. [Asset_Type_Water_Device_Service_Connection]
The domain was not found. [Asset_Type_Water_Device_Rectifier]
The domain was not found. [Asset_Type_Water_Device_Pump]
The domain was not found. [Asset_Type_Water_Device_Pressure_Valve]
The domain was not found. [Asset_Type_Water_Device_Outlet]
The domain was not found. [Asset_Type_Water_Device_Monitoring]
The domain was not found. [Asset_Type_Water_Device_Injection_Facility]
The domain was not found. [Asset_Type_Water_Device_Groundbed]
The domain was not found. [Asset_Type_Water_Device_Flushing_and_Blow_Off]
The domain was not found. [Asset_Type_Water_Device_Flow_Valve]
The domain was not found. [Asset_Type_Water_Device_Fire_Hydrant]
The domain was not found. [Asset_Type_Water_Device_Filter]
The domain was not found. [Asset_Type_Water_Device_Controller]
The domain was not found. [Asset_Type_Water_Device_Anode]
The domain was not found. [Asset_Type_Water_Assembly_Pressure_Reducing_Station]
The domain was not found. [Asset_Type_Water_Assembly_Meter_Station]
The domain was not found. [Asset_Type_Water_Assembly_Hydrant]
The domain was not found. [Asset_Type_Water_Assembly_Horizontal_Valve]
The domain was not found. [Asset_Type_Water_Assembly_Blow_Off]
The domain was not found. [Asset_Type_Water_Assembly_Backflow]
The domain was not found. [Asset_Type_Water_Assembly_Air_Vacuum_and_Air_Release]
The domain was not found. [Asset_Type_Structure_Line_Pipeline_Casing]
The domain was not found. [Asset_Type_Structure_Junction_Pipe_Access_Point]
The domain was not found. [Asset_Type_Structure_Junction_Pipeline_Vault]
The domain was not found. [Asset_Type_Structure_Junction_Pipeline_Valve_Box]
The domain was not found. [Asset_Type_Structure_Junction_Pipeline_Pipe_Support]
The domain was not found. [Asset_Type_Structure_Junction_Pipeline_Pipe_Hanger]
The domain was not found. [Asset_Type_Structure_Junction_Pipeline_Anchor]
The domain was not found. [Asset_Type_Structure_Boundary_Water_Supply_Boundary]
The domain was not found. [Asset_Type_Structure_Boundary_Water_Storage_Boundary]
The domain was not found. [Asset_Type_Structure_Boundary_Water_Pump_Station_Boundary]
The domain was not found. [Asset_Type_Structure_Boundary_Pipeline_Pipe_Vault]
The domain was not found. [Asset_Owner]
The domain was not found. [Asset_Manager]
The domain was not found. [AP_Traversability_Scope]
The domain was not found. [AP_Trace_Types]
The domain was not found. [AP_Topology_Types]
The domain was not found. [AP_Tier_Types]
The domain was not found. [AP_Terminal_Traversability]
The domain was not found. [AP_Terminals_Classes]
The domain was not found. [AP_Subnetwork_Types]
The domain was not found. [AP_Subnetwork_Propagation]
The domain was not found. [AP_Subnetwork_Operators]
The domain was not found. [AP_Subnetwork_Functions]
The domain was not found. [AP_Subnetwork_Filters]
The domain was not found. [AP_Subnetwork_EditModes]
The domain was not found. [AP_Subnetwork_Combinations]
The domain was not found. [AP_Rule_Types]
The domain was not found. [AP_Linear_Classes]
The domain was not found. [AP_Edge_Policy]
The domain was not found. [AP_Domain_Networks]
The domain was not found. [AP_Boolean]
The domain was not found. [AP_Attribute_Types]
The domain was not found. [AP_AttributeRule_Types]
The domain was not found. [AP_Association_Types]
The domain was not found. [AP_Association_Semantics]
The domain was not found. [AP_Association_Roles]
The domain was not found. [AP_Association_Classes]
The domain was not found. [AP_All_Classes]
Failed to execute (ImportXMLWorkspaceDocument).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\shutil.py", line 632, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] Proces nemá přístup k souboru, neboť jej právě využívá jiný proces: 'C:\\Users\\vholubec\\AppData\\Local\\Temp\\ArcGISProTemp30300\\tmpaccno14o\\XML.gdb\\_gdb.NBVHOLUBEC.32428.30300.sr.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projekty\UN\Water_Distribution_Utility_Network_FoundationV1_3\Esri_tools\UtilityDataManagementSupport.atbx\udms_pt\common\wrappers.py", line 161, in wrapper
    f = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projekty\UN\Water_Distribution_Utility_Network_FoundationV1_3\Esri_tools\UtilityDataManagementSupport.atbx\udms_pt\gptools\tools.py", line 118, in run
    out_gdb = change_spat.main(include_tables=include)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projekty\UN\Water_Distribution_Utility_Network_FoundationV1_3\Esri_tools\UtilityDataManagementSupport.atbx\udms_pt\utility_network\ap.py", line 854, in main
    gdb = self.create_new_gdb()
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projekty\UN\Water_Distribution_Utility_Network_FoundationV1_3\Esri_tools\UtilityDataManagementSupport.atbx\udms_pt\utility_network\ap.py", line 761, in create_new_gdb
    with tempfile.TemporaryDirectory() as temp_dir:
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\tempfile.py", line 943, in __exit__
    self.cleanup()
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\tempfile.py", line 947, in cleanup
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\tempfile.py", line 929, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\shutil.py", line 787, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\shutil.py", line 629, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\shutil.py", line 634, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\tempfile.py", line 893, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] Proces nemá přístup k souboru, neboť jej právě využívá jiný proces: 'C:\\Users\\vholubec\\AppData\\Local\\Temp\\ArcGISProTemp30300\\tmpaccno14o\\XML.gdb\\_gdb.NBVHOLUBEC.32428.30300.sr.lock'

**Comment by holubvl3** [comment]
Sorry, adding the video to the last post, where the described behavior is seen.


https://github.com/Esri/Utility-Data-Management-Support-Tools/assets/47881982/9bfbc4f4-63c2-4f2b-bf18-38ea2416d6c5

**Comment by MikeMillerGIS** [comment]
I am on a build more recent that beta 2 and connect repo.  The issue is with import xml failing.  The error about temp file is just the result of import xml failing.

**Comment by pLeBlanc93** [comment]
> The error about temp file is just the result of import xml failing.

We will fix the permission error (simple in python 3.11) but import xml will still fail.

**Comment by holubvl3** [comment]
@pLeBlanc93 / @MikeMillerGIS, thank you. is it worth to logging this issue via EAC for the import XML tool?
